ALTER TABLE "Room" ALTER COLUMN "maxOccupancy" SET DEFAULT 3;

ALTER TABLE "Booking" ADD COLUMN "guestCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Booking" ADD COLUMN "roomCount" INTEGER NOT NULL DEFAULT 1;
